### ISSUE TITLE
issue with Dir

### ISSUE THREAD

**Issue by a1smiith** [kl3jvi/instaDownloader#1]
problem with saving files to Dir

**Comment by kl3jvi** [comment]
Please build and try on a real device :).

**Comment by a1smiith** [comment]
same problem with real device i must restart the device to make files available in gallery
and no Dir with such name "mob_ins_downloader"
when file downloaded and restart the device is appear in gallery with Dir by the name of the url like this:5334243536464
every file have dir with different name

**Comment by kl3jvi** [comment]
You can pull request if you fix it, I dont have much time to make changes recently as I am studying for exams
